dist: xenial
language: python
sudo: false
python:
- 3.5
- 3.6
- 3.7
install:
- pip install -U pip setuptools
- pip install -U pipenv codecov
- pip install -e .
- pipenv install -d --skip-lock --system
script: pytest --cov=aioworkers_sentry
before_deploy:
- echo "__version__ = '$(git describe --tags)'" > aioworkers_sentry/version.py
deploy:
  provider: pypi
  user: abogushov
  on:
    tags: true
    condition: "$TRAVIS_PYTHON_VERSION = 3.6"
  skip_cleanup: true
  password:
    secure: yf4Q7SoLZGHUQINKM4yj9tG9aN0MpUZqShdPfMVFppzy9XZ18sknRviA0jJOYFhY3umoYGdgVU2Rg/SMIwchpK66/SKYYAPdtC4ozpaJMYDApRRQSuOjZtGpnXSI761fOTzPuDUfZWMzlGxHy2AiMie9cBO3wknwj6zsvMYnzzg+tlMjxhP/qp47kafM7JPUB1ALum/oYwnxMqWmtHqioE41zZ01+xJw1EtukAKDky65iiH0UMmLOhchUXwuIC6tn0m5qB6zjl8thOVY5OWfA7JDw23td3fPbhBuLGeLZ9oemUr8XLFYZE2vZQt4fG+KRh7HN8Cl7u2Ugpt12EOLqrNyx2ksTmZ27YgyAjnJaXYndkX9/jftX/mUKtR9BIZTL+mn8oCYeMEvDIg79FrFrrjMhCuPuedT5OFbVSp3C2to0EmkdiUVlb/WkwAiyoB7TtSKg4v3aTDP62AOed1JPEgPrgoOnXzEhqc7A8Tyj8Doo8YTK5Cfe9ffkGcvvbj7oOhw2FMggj0ekRIXk6fQIuElPpd0gHg8QUBRd5sVJFysBy6eHszaPI5Z++YjRXtnS4tQP+VwhrQ4DafPFBBCXIXVvWAqm4/wqeu8vINaxmAr1bUvYCO4qTZbanI3z9Cv9iGrXLx1Nff+8RVmy6Xzu6nMCD2SsRsISLhi/xM1Ruk=
